---
- name: Verify - Existence of {{ item.username }}
  become: true
  ansible.builtin.getent:
    database: passwd
    key: "{{ item.username }}"
    fail_key: true

- name: Verify - Bash is the shell of {{ item.username }}
  ansible.builtin.assert:
    that: ansible_facts.getent_passwd[item.username][5] is match("/bin/bash")

- name: Test sudo permissions for user {{ item.username }}
  become: true
  become_user: "{{ item.username }}"
  ansible.builtin.command:
    cmd: "sudo id"
  register: id_output
  failed_when: false
  changed_when: false

- name: Verify - Sudo permission of {{ item.username }}
  ansible.builtin.assert:
    that: "id_output.rc == {{ 0 if item.sudo else 1 }}"
