---
- name: Verify
  hosts: all
  tasks:
    - name: Verify - Sudoers file is created
      ansible.builtin.include_tasks: verify/sudoers.yml

    - name: Verify - Users are created
      ansible.builtin.include_tasks: verify/user.yml
      loop: "{{ dpa_users }}"
