---
- name: Verify if openssh-server is installed
  become: true
  block:
    - name: Is openssh-server installed?
      ansible.builtin.stat:
        path: "/etc/ssh/sshd_config"
      register: sshd_config

    - name: Verify if openssh-server is installed
      ansible.builtin.assert:
        that: sshd_config.stat.exists

- name: Install DPA certificate authority
  become: true
  block:
    - name: Search for existing TrustedUserCAKeys entry
      ansible.builtin.shell:
        cmd: "grep -oP '(?<=TrustedUserCAKeys ).*' /etc/ssh/sshd_config"
      register: search_trustedusercakeys
      changed_when: false
      failed_when: false

    - name: TrustedUserCAKeys is defined
      when: search_trustedusercakeys.rc == 0
      block:
        - name: Verify certificate authority file already exist
          ansible.builtin.stat:
            path: "{{ search_trustedusercakeys.stdout }}"

        - name: Update certificate authority file with dpa certificate
          ansible.builtin.lineinfile:
            path: "{{ search_trustedusercakeys.stdout }}"
            line: "{{ dpa_ca }}"
            state: present

    - name: TrustedUserCAKeys is not defined
      when: search_trustedusercakeys.rc != 0
      block:
        - name: Create certificate authority file
          ansible.builtin.lineinfile:
            path: "/etc/ssh/trusted_user_ca_keys.pub"
            line: "{{ dpa_ca }}"
            state: present
            create: true
            mode: "0644"

        - name: Update sshd configuration accordingly
          ansible.builtin.lineinfile:
            path: "/etc/ssh/sshd_config"
            line: "TrustedUserCAKeys /etc/ssh/trusted_user_ca_keys.pub"
            state: present
            validate: "sshd -t -f %s"
          register: configure_sshd
          notify:
            - Restart sshd service
