---
- name: Configure DPA user
  when: dpa_username is defined
  become: true
  block:
    - name: Create user {{ dpa_username }}
      ansible.builtin.user:
        name: "{{ dpa_username }}"
        comment: "Cyberark DPA user"
        state: present
        create_home: true

    - name: Grant sudo role to {{ dpa_username }}
      ansible.builtin.lineinfile:
        state: present
        create: true
        mode: "0440"
        path: "/etc/sudoers.d/80-cyberark-dpa"
        line: "{{ dpa_username }} ALL=(ALL) NOPASSWD:ALL"
        validate: "/usr/sbin/visudo -cf %s"
      when: dpa_user_sudo is true
